site_name: Project Project Template
repo_url: https://github.com/puneethabm/puneetha-python-template
repo_name: "puneetha-python-template"
site_description: "Python Project Template"
site_author: "Puneetha Bagivalu Manjegowda"

docs_dir: ../project_docs
site_dir: ../site


nav:
    -   Home: index.md
    -   "Dev Set Up": DEV_SETUP.md
    -   "Project Structure": PROJECT_STRUCTURE.md
    -   "Build process": BUILD_PROCESS.md
    -   "Conventions": CONVENTIONS.md

theme:
    name: material

plugins:
    -   search:
            lang: en